version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - mrdck
  ignore:
  - dependency-name: mockito
    versions:
    - 0.29.0
  - dependency-name: yup-oauth2
    versions:
    - 5.0.1
    - 5.0.2
    - 5.0.3
