[package]
name = "google-bigquery-rs"
version = "0.1.0"
authors = ["Mateusz Perlak <mateuszperlak@mrdck.com>"]
edition = "2018"

[dependencies]
hyper = "^0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "2.0.1"

[dev-dependencies]
mockito = "0.17.1"
