[package]
name = "google-bigquery-rs"
version = "0.1.0"
authors = ["Mateusz Perlak <m.perlak@clearcode.cc>"]
edition = "2018"

[dependencies]
grpc            = "~0.5"
protobuf        = "~2"
futures         = "~0.1"
futures-cpupool = "~0.1"

