[package]
name = "google-bigquery-rs"
version = "0.1.0"
authors = ["mrdck"]
edition = "2018"

[dependencies]
hyper = "^0.10"
hyper-native-tls = "0.3.0"
yup-oauth2 = "5.1.0"

[dev-dependencies]
mockito = "0.17.1"
